[package]
name = "MySocialContracts"
version = "0.1.0"
published-at = ""
edition = "2024"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
MySocial = { local = "../mys-framework" }
seal = { local = "../seal" }

[addresses]
mys = "0x2"
social_contracts = "0xd880"